# Generated by Django 3.1 on 2020-08-28 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cal',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
